# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: SvelteKit Deploy (Dev)

on:
  schedule:
    - cron: '0 * * * 0' # Every Sunday of the month
  push:
    branches: ['flowbite']
  pull_request:
    branches: ['flowbite']
  workflow_dispatch:

concurrency: # Multiple jobs should NOT run at the same time
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -a ubcafe-dev
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          FLY_API_TOKEN: ${{ secrets.FLYIO_ACCESS }}
