# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: SvelteKit Deploy (Staging)

on:
  schedule:
    - cron: '0 * * * 0' # Every Sunday of the month
  push:
    branches: ['staging']
  pull_request:
    branches: ['staging']    
  workflow_dispatch:
     inputs:
      dry_run:
        description: 'Dry run'
        default: false
        required: true
        type: boolean
concurrency: # Multiple jobs should NOT run at the same time
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      FLY_API_TOKEN: ${{ secrets.FLYIO_ACCESS }}
      ENV_FILE: ${{ secrets.ENV_FILE }}
    steps:
      - uses: actions/checkout@v3
      - name: Write Sentry resource file
        run: |
          echo $SENTRY_AUTH_TOKEN >> sentry_token.txt
          echo $ENV_FILE >> .env
          cat .env
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly.io
        if: ${{ inputs.dry_run == false && github.event_name != 'pull_request' }}
        run: | 
         echo "Run RELEASE" >> release
         flyctl deploy --remote-only -a ubcafe
      - name: Run basic test
        if: ${{ inputs.dry_run == true || github.event_name == 'pull_request' }}
        run: docker build -t dishout:latest .
      #- run: flyctl deploy --local-only -a ubcafe
